#yml 文件 与 properties 均可以作为配置文件
#yml 格式文件  属性 与值  中间  一定要有空格    注意层级关系
server:
  port: 8090
  tomcat:
    uri-encoding: utf-8
  servlet:
    context-path: /film

#数据库配置
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/film?characterEncoding=utf-8
    username: root
    password: 123456
  #thymeleaf
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
  #jpa
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
  main:
    allow-bean-definition-overriding: true
  servlet:
    #w文件上传配置
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
mybatis:
  type-aliases-package: com.neu.film.pojo
  mapper-locations: classpath:mapper/*.xml